site_name: ViCalc Help
theme:
  name: material

nav:
  - Home: index.md
  - General: keys_general.md
  - Special: special.md
  - Memory: memory.md
  - Scientific: scientific.md

use_directory_urls: false